// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abilities.sql

package sqlcgen

import (
	"context"
)

const searchAbilities = `-- name: SearchAbilities :many
SELECT
    a.id,
    a.identifier,
    g.identifier AS generation
FROM ability a
JOIN data_set ds ON ds.id = a.data_set_id
JOIN generation g ON g.id = a.generation_id
WHERE a.identifier ILIKE $1::text ESCAPE '\'
    AND ds.identifier = $2::text
ORDER BY a.identifier
`

type SearchAbilitiesParams struct {
	Pattern string
	DataSet string
}

type SearchAbilitiesRow struct {
	ID         int64
	Identifier string
	Generation string
}

func (q *Queries) SearchAbilities(ctx context.Context, arg SearchAbilitiesParams) ([]SearchAbilitiesRow, error) {
	rows, err := q.db.Query(ctx, searchAbilities, arg.Pattern, arg.DataSet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAbilitiesRow
	for rows.Next() {
		var i SearchAbilitiesRow
		if err := rows.Scan(&i.ID, &i.Identifier, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
