// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: effects.sql

package sqlcgen

import (
	"context"
)

const listMoveStatChanges = `-- name: ListMoveStatChanges :many
SELECT msc.move_id, s.identifier AS stat, msc.change
FROM move_stat_change msc
JOIN stat s ON s.id = msc.stat_id
WHERE msc.move_id = ANY($1::bigint[])
ORDER BY msc.move_id, s.id
`

type ListMoveStatChangesRow struct {
	MoveID int64
	Stat   string
	Change int16
}

func (q *Queries) ListMoveStatChanges(ctx context.Context, moveIds []int64) ([]ListMoveStatChangesRow, error) {
	rows, err := q.db.Query(ctx, listMoveStatChanges, moveIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMoveStatChangesRow
	for rows.Next() {
		var i ListMoveStatChangesRow
		if err := rows.Scan(&i.MoveID, &i.Stat, &i.Change); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnknownAilments = `-- name: ListUnknownAilments :many
SELECT p.ailment::text
FROM unnest($1::text[]) AS p(ailment)
WHERE NOT EXISTS (SELECT 1 FROM move_meta mm WHERE mm.ailment = p.ailment)
`

func (q *Queries) ListUnknownAilments(ctx context.Context, ailments []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnknownAilments, ailments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var p_ailment string
		if err := rows.Scan(&p_ailment); err != nil {
			return nil, err
		}
		items = append(items, p_ailment)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnknownStats = `-- name: ListUnknownStats :many
SELECT p.identifier::text
FROM unnest($1::text[]) AS p(identifier)
WHERE NOT EXISTS (SELECT 1 FROM stat s WHERE s.identifier = p.identifier)
`

func (q *Queries) ListUnknownStats(ctx context.Context, identifiers []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnknownStats, identifiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var p_identifier string
		if err := rows.Scan(&p_identifier); err != nil {
			return nil, err
		}
		items = append(items, p_identifier)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMovesByEffect = `-- name: SearchMovesByEffect :many
SELECT
    m.id,
    m.identifier,
    g.identifier AS generation,
    t.identifier AS type,
    m.damage_class,
    m.power,
    m.accuracy,
    m.pp,
    m.priority,
    m.target,
    mm.category,
    mm.ailment,
    mm.ailment_chance,
    mm.stat_chance,
    mm.flinch_chance,
    mm.crit_rate,
    mm.drain,
    mm.healing,
    mm.min_hits,
    mm.max_hits,
    mm.min_turns,
    mm.max_turns
FROM move m
JOIN data_set ds ON ds.id = m.data_set_id
JOIN generation g ON g.id = m.generation_id
JOIN type t ON t.id = m.type_id
LEFT JOIN move_meta mm ON mm.move_id = m.id
WHERE ds.identifier = $1::text
  AND (cardinality($2::text[]) = 0 OR mm.ailment = ALL($2::text[]))
  AND (
      SELECT count(*)
      FROM unnest($3::text[]) WITH ORDINALITY AS si(identifier, n)
      JOIN unnest($4::smallint[]) WITH ORDINALITY AS sc(change, n) ON sc.n = si.n
      JOIN stat s ON s.identifier = si.identifier
      JOIN move_stat_change msc
        ON msc.move_id = m.id AND msc.stat_id = s.id AND msc.change = sc.change
  ) = cardinality($3::text[])
ORDER BY m.identifier
`

type SearchMovesByEffectParams struct {
	DataSet         string
	Ailments        []string
	StatIdentifiers []string
	StatChanges     []int16
}

type SearchMovesByEffectRow struct {
	ID            int64
	Identifier    string
	Generation    string
	Type          string
	DamageClass   string
	Power         *int16
	Accuracy      *int16
	Pp            int16
	Priority      int16
	Target        string
	Category      *string
	Ailment       *string
	AilmentChance *int16
	StatChance    *int16
	FlinchChance  *int16
	CritRate      *int16
	Drain         *int16
	Healing       *int16
	MinHits       *int16
	MaxHits       *int16
	MinTurns      *int16
	MaxTurns      *int16
}

func (q *Queries) SearchMovesByEffect(ctx context.Context, arg SearchMovesByEffectParams) ([]SearchMovesByEffectRow, error) {
	rows, err := q.db.Query(ctx, searchMovesByEffect,
		arg.DataSet,
		arg.Ailments,
		arg.StatIdentifiers,
		arg.StatChanges,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMovesByEffectRow
	for rows.Next() {
		var i SearchMovesByEffectRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Generation,
			&i.Type,
			&i.DamageClass,
			&i.Power,
			&i.Accuracy,
			&i.Pp,
			&i.Priority,
			&i.Target,
			&i.Category,
			&i.Ailment,
			&i.AilmentChance,
			&i.StatChance,
			&i.FlinchChance,
			&i.CritRate,
			&i.Drain,
			&i.Healing,
			&i.MinHits,
			&i.MaxHits,
			&i.MinTurns,
			&i.MaxTurns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
