// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
)

const searchItems = `-- name: SearchItems :many
SELECT
    i.id,
    i.identifier,
    i.category,
    i.fling_power
FROM item i
JOIN data_set ds ON ds.id = i.data_set_id
WHERE i.identifier ILIKE $1::text ESCAPE '\'
  AND ds.identifier = $2::text
ORDER BY i.identifier
`

type SearchItemsParams struct {
	Pattern string
	DataSet string
}

type SearchItemsRow struct {
	ID         int64
	Identifier string
	Category   string
	FlingPower *int16
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error) {
	rows, err := q.db.Query(ctx, searchItems, arg.Pattern, arg.DataSet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsRow
	for rows.Next() {
		var i SearchItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Category,
			&i.FlingPower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
