// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Ability struct {
	ID           int64
	DataSetID    int64
	Identifier   string
	GenerationID int64
}

type DataSet struct {
	ID         int64
	Identifier string
	ParentID   *int64
}

type Generation struct {
	ID         int64
	Identifier string
	Number     int16
}

type Item struct {
	ID         int64
	DataSetID  int64
	Identifier string
	Category   string
	FlingPower *int16
}

type Move struct {
	ID           int64
	DataSetID    int64
	Identifier   string
	GenerationID int64
	TypeID       int64
	DamageClass  string
	Power        *int16
	Accuracy     *int16
	Pp           int16
	Priority     int16
	Target       string
}

type MoveMetum struct {
	MoveID        int64
	DataSetID     int64
	Category      string
	Ailment       string
	MinHits       *int16
	MaxHits       *int16
	MinTurns      *int16
	MaxTurns      *int16
	Drain         int16
	Healing       int16
	CritRate      int16
	AilmentChance int16
	FlinchChance  int16
	StatChance    int16
}

type MoveStatChange struct {
	MoveID    int64
	DataSetID int64
	StatID    int64
	Change    int16
}

type Nature struct {
	ID              int64
	Identifier      string
	IncreasedStatID *int64
	DecreasedStatID *int64
}

type Species struct {
	ID                 int64
	Identifier         string
	NationalDex        int16
	IsDefault          bool
	GenerationID       int64
	Type1ID            int64
	Type2ID            *int64
	BaseHp             int16
	BaseAttack         int16
	BaseDefense        int16
	BaseSpecialAttack  int16
	BaseSpecialDefense int16
	BaseSpeed          int16
}

type Stat struct {
	ID           int64
	Identifier   string
	IsBattleOnly bool
}

type Type struct {
	ID           int64
	Identifier   string
	GenerationID int64
}
