// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moves.sql

package sqlcgen

import (
	"context"
)

const searchMoves = `-- name: SearchMoves :many
SELECT
    m.id,
    m.identifier,
    g.identifier AS generation,
    t.identifier AS type,
    m.damage_class,
    m.power,
    m.accuracy,
    m.pp,
    m.priority,
    m.target
FROM move m
JOIN data_set ds ON ds.id = m.data_set_id
JOIN generation g ON g.id = m.generation_id
JOIN type t ON t.id = m.type_id
WHERE m.identifier ILIKE $1::text ESCAPE '\'
  AND ds.identifier = $2::text
ORDER BY m.identifier
`

type SearchMovesParams struct {
	Pattern string
	DataSet string
}

type SearchMovesRow struct {
	ID          int64
	Identifier  string
	Generation  string
	Type        string
	DamageClass string
	Power       *int16
	Accuracy    *int16
	Pp          int16
	Priority    int16
	Target      string
}

func (q *Queries) SearchMoves(ctx context.Context, arg SearchMovesParams) ([]SearchMovesRow, error) {
	rows, err := q.db.Query(ctx, searchMoves, arg.Pattern, arg.DataSet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMovesRow
	for rows.Next() {
		var i SearchMovesRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Generation,
			&i.Type,
			&i.DamageClass,
			&i.Power,
			&i.Accuracy,
			&i.Pp,
			&i.Priority,
			&i.Target,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
