// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package sqlcgen

import (
	"context"
)

const searchSpecies = `-- name: SearchSpecies :many
SELECT
    s.id,
    s.identifier,
    s.national_dex,
    s.is_default,
    g.identifier AS generation,
    t1.identifier AS type_1,
    t2.identifier AS type_2,
    s.base_hp,
    s.base_attack,
    s.base_defense,
    s.base_special_attack,
    s.base_special_defense,
    s.base_speed
FROM species s
JOIN generation g ON g.id = s.generation_id
JOIN type t1 ON t1.id = s.type_1_id
LEFT JOIN type t2 ON t2.id = s.type_2_id
WHERE s.identifier ILIKE $1::text ESCAPE '\'
ORDER BY s.national_dex, s.identifier
`

type SearchSpeciesRow struct {
	ID                 int64
	Identifier         string
	NationalDex        int16
	IsDefault          bool
	Generation         string
	Type1              string
	Type2              *string
	BaseHp             int16
	BaseAttack         int16
	BaseDefense        int16
	BaseSpecialAttack  int16
	BaseSpecialDefense int16
	BaseSpeed          int16
}

func (q *Queries) SearchSpecies(ctx context.Context, pattern string) ([]SearchSpeciesRow, error) {
	rows, err := q.db.Query(ctx, searchSpecies, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSpeciesRow
	for rows.Next() {
		var i SearchSpeciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.NationalDex,
			&i.IsDefault,
			&i.Generation,
			&i.Type1,
			&i.Type2,
			&i.BaseHp,
			&i.BaseAttack,
			&i.BaseDefense,
			&i.BaseSpecialAttack,
			&i.BaseSpecialDefense,
			&i.BaseSpeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
